name: 'user-web'
port: 8021

user_srv:
  host: '127.0.0.1'
  port: 50051
  name: 'user_srv'


jwt:
  key: '5YaQ6KC58y$#$MkGNBHCz#!4Ws6'

redis:
  host: '127.0.0.1'
  port: 6379
  db: 0

sms:
  len: 6
  expire: 60

consul:
  host: '127.0.0.1'
  port: 8500
