name: 'user-web'
userSrv:
  host: '127.0.0.1'
  port: 50051
  prefix: '/user'
  debug: true
  log:
    level: 'debug'
    path: 'logs/user-web.log'
    maxsize: 100
    maxbackups: 5
    maxage: 30
    compress: true
