name: dev
channels:
  - pdrops
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohttp=3.9.5
  - aiosignal=1.2.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - async-timeout=4.0.3
  - attrs=23.1.0
  - bcrypt=3.2.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.3.11
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - cryptography=42.0.5
  - deprecated=1.2.13
  - frozenlist=1.4.0
  - grpcio=1.62.2
  - grpcio-health-checking=1.62.2
  - grpcio-tools=1.62.2
  - idna=3.7
  - ld_impl_linux-64=2.38
  - libabseil=20240116.1
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgrpc=1.62.2
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsqlite=3.45.2
  - libstdcxx-ng=13.2.0
  - libuuid=1.41.5
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - loguru=0.5.3
  - multidict=6.0.4
  - ncurses=6.4
  - openssl=3.2.1
  - packaging=23.2
  - passlib=1.7.4
  - peewee=3.17.1
  - pip=24.0
  - protobuf=4.25.3
  - py-consul=1.3.0
  - pycparser=2.21
  - pymysql=1.0.2
  - pysocks=1.7.1
  - python=3.10.14
  - python_abi=3.10
  - re2=2023.09.01
  - readline=8.2
  - redis-py=4.3.4
  - requests=2.31.0
  - setuptools=69.5.1
  - six=1.16.0
  - sqlite=3.45.3
  - tk=8.6.14
  - types-futures=3.3.8
  - types-protobuf=4.23.0.1
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024a
  - urllib3=2.2.1
  - wheel=0.43.0
  - wrapt=1.14.1
  - xz=5.4.6
  - yarl=1.9.3
  - zlib=1.2.13
  - pip:
    - nacos-sdk-python==0.1.14
